### ISSUE TITLE
Algorithms 1 Coursera Princeton

### ISSUE THREAD

**Issue by waterlooSunset** [open-source-society/computer-science-and-engineering#12]
I'm currently completing this course @ Coursera, part of the agreement for completing the course is that students will not publicly post solutions to course material. I'd like to respect this request but still would like to demonstrate what I've learned in the class. Perhaps this course should have an OSS specific test the incorporates the concepts of the course without using its content, thereby avoiding encouraging students to violate the academic honesty agreement they sign at the begging of class?

**Comment by ericdouglas** [comment]
In that case, we should make public only the materials that do not violate those terms. We can create a project after finish the course to show what we learn, in that way everything will be fine. :smile:

**Comment by waterlooSunset** [comment]
I think what you propose is a really good solution. 

What kind of project do you think would help test basic understanding of the course material?

 Each course component has a number of non-graded and unanswered "interview questions" and challenges that we've been discussing in the forum for this class session. They do a good job at getting one to apply the lecture material. 

If you think it would be helpful I can write some basic data structure 'tests' based on these in mocha.js (I'm a mostly a javascript person right now) in my fork of the curriculum while I finish the course. Something along the lines of [js-assessment](https://github.com/rmurphey/js-assessment) but for Algorithms 1

**Comment by ericdouglas** [comment]
@waterlooSunset it's difficult to suggest projects, because each course teach something, and each student has a different expertise on programming.

When I tell about projects, I think something like [this](https://github.com/ericdouglas/app-specs).

About the tests, this would be great! I did something similar [here](https://github.com/ericdouglas/courses/tree/master/freecodecamp/bonfires), and it can help a lot!

Let's keep in touch and together we can think in great projects to validate our knowledge in each course. :smile: 

There are [these](https://github.com/karan/Projects) ideas too.
