### ISSUE TITLE
Student Profile

### ISSUE THREAD

**Issue by jennelyn** [open-source-society/computer-science-and-engineering#69]
Name: Jennelyn Medianista
GitHub: @jennelyn
Twitter:
Linkedin: 
Website:

**Comment by Ekrow** [comment]
You probably meant to post here: https://github.com/open-source-society/computer-science-and-engineering/issues/31

**Comment by ericdouglas** [comment]
@Ekrow many thanks for helping! Just one thing, try to not make a direct reference to the `#31` issue, because this will appear there, and is a little dirty and confusing have many references in that issue.

You can use something like: You probably meant to post here: `#31`

Anyway, **thank you so much** for helping with this :smile:
